DROP TABLE DELIVERY.AGENDAMENTO_ENTREGAS;
DROP TABLE DELIVERY.ENTREGAS;
DROP TABLE DELIVERY.CLIENTES;
DROP TABLE DELIVERY.FUNCIONARIOS;

DROP SEQUENCE DELIVERY.SQ_AGENDAMENTO_ENTREGAS;
DROP SEQUENCE DELIVERY.SQ_ENTREGAS;
DROP SEQUENCE DELIVERY.SQ_CLIENTES;
DROP SEQUENCE DELIVERY.SQ_FUNCIONARIOS;